---
# task/configure file for hashicorp_vault
- name: "Vault | Create vault.env"
  ansible.builtin.template:
    src: vault.env.j2
    dest: "{{ hashicorp_vault_config_dir }}/vault.env"
    owner: "{{ hashicorp_vault_user }}"
    group: "{{ hashicorp_vault_group }}"
    mode: "0600"
  register: _hashicorp_vault_env_file

- name: "Vault | Copy vault.json template"
  ansible.builtin.template:
    src: vault.json.j2
    dest: "{{ hashicorp_vault_config_dir }}/vault.json"
    owner: "{{ hashicorp_vault_user }}"
    group: "{{ hashicorp_vault_group }}"
    mode: "0600"
  register: _hashicorp_vault_config_file

- name: "Vault | Set restart-check variable"
  ansible.builtin.set_fact:
    _hashicorp_vault_service_need_restart: true
  when: _hashicorp_vault_env_file.changed or
    _hashicorp_vault_config_file.changed

- name: "Vault | Copy extra configuration files"
  when: hashicorp_vault_extra_files
  block:
    - name: "Vault | Get extra file types"
      ansible.builtin.stat:
        path: "{{ item.src }}"
      loop: "{{ hashicorp_vault_extra_files_list }}"
      register: hashicorp_vault_extra_file_stat
      delegate_to: localhost

    - name: "Vault | Set list for file sources"
      vars:
        _hashicorp_vault_file_sources: []
      ansible.builtin.set_fact:
        _hashicorp_vault_file_sources: "{{ _hashicorp_vault_file_sources + [item.item] }}"
      when: item.stat.isreg
      loop: "{{ hashicorp_vault_extra_file_stat.results }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    - name: "Vault | Set list for directory sources"
      vars:
        _hashicorp_vault_dir_sources: []
      ansible.builtin.set_fact:
        _hashicorp_vault_dir_sources: "{{ _hashicorp_vault_dir_sources + [item.item] }}"
      when: item.stat.isdir
      loop: "{{ hashicorp_vault_extra_file_stat.results }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    - name: "Vault | Template extra file sources"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest | regex_replace('\\.j2$', '') }}"
        owner: "{{ hashicorp_vault_user }}"
        group: "{{ hashicorp_vault_group }}"
        mode: "0700"
      loop: "{{ _hashicorp_vault_file_sources }}"
      when: _hashicorp_vault_file_sources is defined

    - name: "Vault | Template extra directory sources"
      ansible.builtin.include_tasks: recursive_copy_extra_dirs.yml
      loop: "{{ _hashicorp_vault_dir_sources }}"
      loop_control:
        loop_var: dir_source_item
      when: _hashicorp_vault_dir_sources is defined
