---
# task/configure file for hashicorp_vault
- name: "Configure for host installation"
  when: hashi_vault_deploy_method == 'host'
  block:
    - name: "Ensure default vault.hcl is removed"
      ansible.builtin.file:
        path: /etc/vault.d/vault.hcl
        state: absent

    - name: "Create vault.env"
      ansible.builtin.template:
        src: vault.env.j2
        dest: "{{ hashi_vault_config_dir }}/vault.env"
        owner: "{{ hashi_vault_user }}"
        group: "{{ hashi_vault_group }}"
        mode: "0600"

- name: "Copy vault.json template"
  ansible.builtin.template:
    src: vault.json.j2
    dest: "{{ hashi_vault_config_dir }}/vault.json"
    owner: "{{ hashi_vault_user }}"
    group: "{{ hashi_vault_group }}"
    mode: "0600"
  notify:
    - "systemctl-enable-vault"
    - "systemctl-restart-vault"

- name: "Copy extra configuration files"
  when: hashi_vault_extra_files
  block:
    - name: "Update container volume list"
      ansible.builtin.set_fact:
        hashi_vault_container_volume_map: "{{
          (hashi_vault_container_volume_map + [
          item.dest + ':' + item.dest
          ]) | unique }}"
      loop: "{{ hashi_vault_extra_files_list }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    - name: "Get extra file types"
      ansible.builtin.stat:
        path: "{{ item.src }}"
      loop: "{{ hashi_vault_extra_files_list }}"
      register: hashi_vault_extra_file_stat
      delegate_to: localhost

    - name: "Set list for file sources"
      vars:
        _hashi_vault_file_sources: []
      ansible.builtin.set_fact:
        _hashi_vault_file_sources: "{{ _hashi_vault_file_sources + [item.item] }}"
      when: item.stat.isreg
      loop: "{{ hashi_vault_extra_file_stat.results }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    - name: "Set list for directory sources"
      vars:
        _hashi_vault_dir_sources: []
      ansible.builtin.set_fact:
        _hashi_vault_dir_sources: "{{ _hashi_vault_dir_sources + [item.item] }}"
      when: item.stat.isdir
      loop: "{{ hashi_vault_extra_file_stat.results }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    - name: "Template extra file sources"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest | regex_replace('\\.j2$', '') }}"
        owner: "{{ hashi_vault_user }}"
        group: "{{ hashi_vault_group }}"
        mode: "0700"
      loop: "{{ _hashi_vault_file_sources }}"

    - name: "Template extra directory sources"
      ansible.builtin.include_tasks: recursive_copy_extra_dirs.yml
      loop: "{{ _hashi_vault_dir_sources }}"
      loop_control:
        loop_var: dir_source_item
