---
# task/configure file for hashicorp_vault
- name: "Configure for host installation"
  when: hashi_vault_deploy_method == 'host'
  block:
    - name: "Ensure default vault.hcl is removed"
      ansible.builtin.file:
        path: /etc/vault.d/vault.hcl
        state: absent

    - name: "Create vault.env"
      ansible.builtin.template:
        src: vault.env.j2
        dest: "{{ hashi_vault_config_dir }}/vault.env"
        owner: "{{ hashi_vault_user }}"
        group: "{{ hashi_vault_group }}"
        mode: '0600'

- name: "Copy vault.json template"
  ansible.builtin.template:
    src: vault.json.j2
    dest: "{{ hashi_vault_config_dir }}/vault.json"
    owner: "{{ hashi_vault_user }}"
    group: "{{ hashi_vault_group }}"
    mode: '0600'
  notify:
    - "systemctl-enable-vault"
    - "systemctl-restart-vault"

- name: "Copy extra configuration files"
  when: hashi_vault_extra_files
  block:
    - name: "Update container volume list"
      ansible.builtin.set_fact:
        hashi_vault_container_volume_map: "{{
          (hashi_vault_container_volume_map + [
          hashi_vault_extra_files_dst + ':' + hashi_vault_extra_files_dst
          ]) | unique }}"

    - name: "Create directory {{ hashi_vault_extra_files_dst }}"
      ansible.builtin.file:
        path: "{{ hashi_vault_extra_files_dst }}"
        state: directory
        owner: "{{ hashi_vault_user }}"
        group: "{{ hashi_vault_group }}"
        mode: '0755'

    - name: "Copy extra configuration files"
      ansible.builtin.copy:
        src: "{{ hashi_vault_extra_files_src }}/"
        dest: "{{ hashi_vault_extra_files_dst }}/"
        owner: "{{ hashi_vault_user }}"
        group: "{{ hashi_vault_group }}"
        mode: '0600'

    - name: "Set permissions for directories"
      ansible.builtin.find:
        paths: "{{ hashi_vault_extra_files_dst }}"
        recurse: yes
        file_type: directory
      register: directories_to_set_permissions

    - name: "Set permissions for directories"
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: '0755'
      with_items: "{{ directories_to_set_permissions.files }}"
      when: directories_to_set_permissions.matched > 0
