---
# task/main file for hashicorp_vault
- name: "Set reload-check & restart-check variable"
  ansible.builtin.set_fact:
    _hashi_vault_service_need_reload: false
    _hashi_vault_service_need_restart: false

- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import install.yml"
  ansible.builtin.include_tasks: "install.yml"

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml

- name: "Enable service: {{ hashi_vault_service_name }}"
  ansible.builtin.service:
    name: "{{ hashi_vault_service_name }}"
    enabled: true

- name: "Reload systemd daemon"
  ansible.builtin.systemd:
    daemon_reload: true
  when: _hashi_vault_service_need_reload

- name: "Start service: {{ hashi_vault_service_name }}"
  ansible.builtin.service:
    name: "{{ hashi_vault_service_name }}"
    state: restarted
  throttle: 1
  when: _hashi_vault_service_need_restart
