---
# task/main file for hashicorp_vault
- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import install_host.yml"
  ansible.builtin.include_tasks: "install_host.yml"
  when: hashi_vault_deploy_method == 'host'

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml

- name: "Import install_docker.yml"
  ansible.builtin.include_tasks: "install_docker.yml"
  when: hashi_vault_deploy_method == 'docker'

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
