---
# defaults file for hashicorp_vault

#########################
# storage configuration #
#########################

hashicorp_vault_storage_configuration:
  raft:
    path: "{{ hashicorp_vault_data_dir }}"
    node_id: "{{ ansible_hostname }}"
    retry_join:
      - leader_api_addr: "http://{{ hashicorp_vault_cluster_addr }}:8200"
