---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Include ednz_cloud.install_docker"
      ansible.builtin.include_role:
        name: ednz_cloud.install_docker
      vars:
        install_docker_python_packages: true

    - name: "Create directory /opt/vault/tls"
      ansible.builtin.file:
        path: "/opt/vault/tls"
        state: directory
        owner: "100"
        group: "1000"
        mode: '0755'
