---

hashi_vault_deploy_method: docker  # deployment method, either host or docker
hashi_vault_configuration:
  cluster_name: vault
  cluster_addr: "http://127.0.0.1:8201"
  api_addr: "http://127.0.0.1:8200"
  ui: true
  disable_mlock: false
  disable_cache: false
  listener:
    tcp:
      address: "127.0.0.1:8200"
      cluster_address: "127.0.0.1:8201"
      tls_disable: true
  storage:
    file:
      path: "/vault/data"
  telemetry:
    usage_gauge_period: 10m
    maximum_gauge_cardinality: 500
    disable_hostname: false
    enable_hostname_label: false
    lease_metrics_epsilon: 1h
    num_lease_metrics_buckets: 168
    add_lease_metrics_namespace_labels: false
    filter_default: true
    prefix_filter: []
    prometheus_retention_time: 24h
